/*******************************************************************************
* KindEditor - WYSIWYG HTML Editor for Internet
* Copyright (C) 2006-2011 kindsoft.net
*
* @author Roddy <luolonghao@gmail.com>
* @site http://www.kindsoft.net/
* @licence http://www.kindsoft.net/license.php
* @russian Sergomanov Dmitry http://www.adatum.ru
*******************************************************************************/

KindEditor.lang({
	source : 'Код',
	preview : 'Предпросмотр',
	undo : 'Отменить(Ctrl+Z)',
	redo : 'Повторить(Ctrl+Y)',
	cut : 'Вырезать(Ctrl+X)',
	copy : 'Скопировать(Ctrl+C)',
	paste : 'Вставить(Ctrl+V)',
	plainpaste : 'Вставить как текст',
	wordpaste : 'Вставить слово',
	selectall : 'Выбрать все',
	justifyleft : 'Выровнять по левому краю',
	justifycenter : 'Выровнять по центру',
	justifyright : 'Выровнять по правому краю',
	justifyfull : 'Выровнять по ширине',
	insertorderedlist : 'Нумерованный список',
	insertunorderedlist : 'Неупорядоченный список',
	indent : 'Увеличить отступ',
	outdent : 'Уменьшить отступ',
	subscript : 'Индекс',
	superscript : 'Верхний индекс',
	formatblock : 'Формат параграфа',
	fontname : 'Шрифт',
	fontsize : 'Размер шрифта',
	forecolor : 'Цвет текста',
	hilitecolor : 'Highlight color',
	bold : 'Жирный(Ctrl+B)',
	italic : 'Курсив(Ctrl+I)',
	underline : 'Подчеркнутый(Ctrl+U)',
	strikethrough : 'Зачеркнутый',
	removeformat : 'Удалить форматирование',
	image : '',
	multiimage : 'Серия изображений',
	flash : 'Флэш',
	media : 'Вставить медиа файл',
	table : 'Таблица',
	tablecell : 'Ячейка',
	hr : 'Вставьте горизонтальную линию',
	emoticons : 'Вставить смайлик',
	link : 'Ссылка',
	unlink : 'Удалить ссылку',
	fullscreen : 'Переключить в полноэкранный режим',
	about : 'Информация',
	print : 'Печать',
	filemanager : 'Файловый менеджер',
	code : 'Вставить код',
	map : 'Google карты',
	lineheight : 'Высота линии',
	clearhtml : 'Очистить HTML код',
	pagebreak : 'Вставить разрыв страницы',
	quickformat : 'Быстрое форматирование',
	insertfile : 'Вставить файл',
	template : 'Вставить из шаблона',
	anchor : 'Якорь',
	yes : 'Да',
	no : 'Отмена',
	close : 'Закрыть',
	editImage : 'Свойства',
	deleteImage : 'Удалить',
	editFlash : 'Флэш свойства',
	deleteFlash : 'Удалить Флэш',
	editMedia : 'Медиа свойства',
	deleteMedia : 'Удалить медиа',
	editLink : 'Свойства ссылки',
	deleteLink : 'Удалить ссылку',
	tableprop : 'Свойства таблицы',
	tablecellprop : 'Свойства ячеек',
	tableinsert : 'Вставить таблицу',
	tabledelete : 'Удалить таблицу',
	tablecolinsertleft : 'Вставить столбец слева',
	tablecolinsertright : 'Вставить столбец справа',
	tablerowinsertabove : 'Вставить строку выше',
	tablerowinsertbelow : 'Вставить строку ниже',
	tablerowmerge : 'Объединить с предыдущим',
	tablecolmerge : 'Объединить справа',
	tablerowsplit : 'Разбить строку',
	tablecolsplit : 'Разбить колонку',
	tablecoldelete : 'Удалить столбец',
	tablerowdelete : 'Удалить строку',
	noColor : 'По умолчанию',
	pleaseSelectFile : 'Пожалуйста, выберите файл.',
	invalidImg : "Пожалуйста, введите действующий URL.\nРазрешенные расширения файлов: jpg,gif,bmp,png",
	invalidMedia : "Пожалуйста, введите действующий URL.\nРазрешенные расширения файлов: swf,flv,mp3,wav,wma,wmv,mid,avi,mpg,asf,rm,rmvb",
	invalidWidth : "Ширина должна быть числом.",
	invalidHeight : "Высота должна быть числом.",
	invalidBorder : "Граница должна быть числом.",
	invalidUrl : "Пожалуйста, введите действительный URL.",
	invalidRows : 'Неверная строка.',
	invalidCols : 'Неверный столбец.',
	invalidPadding : 'Отступ должен быть числом.',
	invalidSpacing : 'Расстояние должно быть числом.',
	invalidJson : 'Неверная JSON строка.',
	uploadSuccess : 'Загрузка прошла успешно.',
	cutError : 'В настоящее время не поддерживается вашим браузером, используйте сочетание клавиш (Ctrl + X) вместо этого.',
	copyError : 'В настоящее время не поддерживается вашим браузером, используйте сочетание клавиш (Ctrl + С) вместо этого.',
	pasteError : 'В настоящее время не поддерживается вашим браузером, используйте сочетание клавиш (Ctrl + V) вместо этого.',
	ajaxLoading : 'Загрузка ...',
	uploadLoading : 'Загрузка ...',
	uploadError : 'Ошибка при загрузке',
	'plainpaste.comment' : 'Используйте сочетание клавиш (Ctrl + V), чтобы вставить текст в окно.',
	'wordpaste.comment' : 'Используйте сочетание клавиш (Ctrl + V), чтобы вставить текст в окно.',
	'code.pleaseInput' : 'Пожалуйста, введите код.',
	'link.url' : 'URL',
	'link.linkType' : 'Тип',
	'link.newWindow' : 'В новом окне',
	'link.selfWindow' : 'В этом же окне',
	'flash.url' : 'URL',
	'flash.width' : 'Ширина',
	'flash.height' : 'Высота',
	'flash.upload' : 'Загрузить',
	'flash.viewServer' : 'Обзор',
	'media.url' : 'URL',
	'media.width' : 'Ширина',
	'media.height' : 'Высота',
	'media.autostart' : 'Автоматический запуск',
	'media.upload' : 'Загрузить',
	'media.viewServer' : 'Обзор',
	'image.remoteImage' : 'Вставить URL',
	'image.localImage' : 'Загрузить',
	'image.remoteUrl' : 'URL',
	'image.localUrl' : 'Файл',
	'image.size' : 'Размер',
	'image.width' : 'Ширина',
	'image.height' : 'Высота',
	'image.resetSize' : 'Получить размеры',
	'image.align' : 'Выровнять',
	'image.defaultAlign' : 'По умолчанию',
	'image.leftAlign' : 'Лево',
	'image.rightAlign' : 'Право',
	'image.imgTitle' : 'Название',
	'image.upload' : 'Обзор',
	'image.viewServer' : 'Обзор',
	'multiimage.uploadDesc' : 'Можно загрузить <%=uploadLimit%> изображений, размером <%=sizeLimit%>',
	'multiimage.startUpload' : 'Загрузить',
	'multiimage.clearAll' : 'Очистить все',
	'multiimage.insertAll' : 'Вставьте все',
	'multiimage.queueLimitExceeded' : 'Предел очереди превышен.',
	'multiimage.fileExceedsSizeLimit' : 'Размер файла превышает предельный размер.',
	'multiimage.zeroByteFile' : 'Файл нулевого размера.',
	'multiimage.invalidFiletype' : 'Неверный тип файла.',
	'multiimage.unknownError' : 'Неизвестная ошибка загрузки.',
	'multiimage.pending' : 'Ожидание ...',
	'multiimage.uploadError' : 'Ошибка при загрузке',
	'filemanager.emptyFolder' : 'Пустой',
	'filemanager.moveup' : 'Родительская папка',
	'filemanager.viewType' : 'Отображать: ',
	'filemanager.viewImage' : 'Миниатюры',
	'filemanager.listImage' : 'Список',
	'filemanager.orderType' : 'Сортировка: ',
	'filemanager.fileName' : 'По имени',
	'filemanager.fileSize' : 'По размеру',
	'filemanager.fileType' : 'По типу',
	'insertfile.url' : 'URL',
	'insertfile.title' : 'Название',
	'insertfile.upload' : 'Загрузить',
	'insertfile.viewServer' : 'Обзор',
	'table.cells' : 'Ячейка',
	'table.rows' : 'Строки',
	'table.cols' : 'Cтолбец',
	'table.size' : 'Размеры',
	'table.width' : 'Ширина',
	'table.height' : 'Высота',
	'table.percent' : '%',
	'table.px' : 'px',
	'table.space' : 'Место',
	'table.padding' : 'Заполнение',
	'table.spacing' : 'Интервал',
	'table.align' : 'Выровнять',
	'table.textAlign' : 'Горизонтально',
	'table.verticalAlign' : 'Вертикально',
	'table.alignDefault' : 'По умолчанию',
	'table.alignLeft' : 'Слева',
	'table.alignCenter' : 'Центр',
	'table.alignRight' : 'Право',
	'table.alignTop' : 'Вверх',
	'table.alignMiddle' : 'По середине',
	'table.alignBottom' : 'Вниз',
	'table.alignBaseline' : 'Базовая линия',
	'table.border' : 'Граница',
	'table.borderWidth' : 'Ширина',
	'table.borderColor' : 'Цвет',
	'table.backgroundColor' : 'Фон',
	'map.address' : 'Адрес: ',
	'map.search' : 'Поиск',
	'anchor.name' : 'Имя якоря',
	'formatblock.formatBlock' : {
		h1 : 'Заголовок 1',
		h2 : 'Заголовок 2',
		h3 : 'Заголовок 3',
		h4 : 'Заголовок 4',
		p : 'Нормальный'
	},
	'fontname.fontName' : {
		'Arial' : 'Arial',
		'Arial Black' : 'Arial Black',
		'Comic Sans MS' : 'Comic Sans MS',
		'Courier New' : 'Courier New',
		'Garamond' : 'Garamond',
		'Georgia' : 'Georgia',
		'Tahoma' : 'Tahoma',
		'Times New Roman' : 'Times New Roman',
		'Trebuchet MS' : 'Trebuchet MS',
		'Verdana' : 'Verdana'
	},
	'lineheight.lineHeight' : [
		{'1' : 'Высота линии 1'},
		{'1.5' : 'Высота линии 1.5'},
		{'2' : 'Высота линии 2'},
		{'2.5' : 'Высота линии 2.5'},
		{'3' : 'Высота линии 3'}
	],
	'template.selectTemplate' : 'Шаблон',
	'template.replaceContent' : 'Заменить текущее содержание',
	'template.fileList' : {
		'1.html' : 'Изображение и текст',
		'2.html' : 'Таблица',
		'3.html' : 'Список'
	}
}, 'ru_Ru');
